### ISSUE TITLE
Create DALTON-like grammar for input parsing

### ISSUE THREAD

**Issue by robertodr** [dev-cafe/parselglossy#10]
Much as in #8: to show off the generality of our approach and be a drop-in replacement for the DALTON input parser.

**Comment by robertodr** [comment]
Some notes/_desiderata_:
- The atom for floating point numbers should allow for the use of `D`/`d` for numbers in scientific notation. Despite the fact that I really dislike this Fortran-ism, we must have this for parselglossy to be a zero-hassle replacement to the current parser in DALTON/LSDALTON.
- Lists are specified like this:
```
.A_LIST
<number of elements>
<el1> <el2> ... <elN>
```
this is due to the fact that we need how many consecutive tokens to read on the line before moving on to the next line. I'd like to deprecate this format in favor of just:
```
.A_LIST
<el1> <el2> ... <elN>
```
the atom for lists would then have the first number as optionally present. If present, it can be used to check the length of the list matches; if not, it's still OK.
- Imaginary parts of the frequencies are specified by duplicating lists. I think this can be deprecated in favor of having one list of complex numbers. 
- Booleans might also be improved to be more explicit. Deprecate:
```
.RH
.DIIS
```
to encourage use of:
```
.RH
True
.DIIS
True
```

True to the tagline for this project (_speaking in tongues_) I would like to completely phase out the current format and move to the Getkw format. I think our design makes it possible.

**Comment by bast** [comment]
Sometimes lists are provided by this form:
```
.A_LIST
<number of elements>
<el1>
<el2>
...
<elN>
```

**Comment by bast** [comment]
Giving up on this. We might return to this but I want to first see interest and buy-in from (LS)Dalton communities before investing a lot of time into this.
