### ISSUE TITLE
GitHub Action producin PyPI package does not trigger on release

### ISSUE THREAD

**Issue by robertodr** [dev-cafe/parselglossy#103]
I prepared and published v0.5.0, but the action was not triggered and thus no PyPI package uploaded.

**Comment by bast** [comment]
Weird ... looking at it.

**Comment by bast** [comment]
First time I see this not working. I tried it here and it works: https://github.com/bast/just-testing/actions (same repo just pushed to a new address).

So how did you create the release? Apparently differently than what I do.

**Comment by bast** [comment]
Is GitHub confused about a leftover workflow with the same name?

**Comment by robertodr** [comment]
I think I tagged by hand, rather than through the web UI. And it happened through Travis. We never tagged after switching to GH actions and the workflow was never tested.

**Comment by bast** [comment]
I always use web UI these days for releases so maybe something is missing for when tags are pushed via command line. I will test that in my throwaway repo.

**Comment by bast** [comment]
Confirmed: this doesn't do anything when a tag is pushed. I don't know, let's create them through web UI?

**Comment by robertodr** [comment]
But 0.5.0 was created through the web UI

**Comment by bast** [comment]
Then it's some interaction with leftover workflow from earlier? I don't know. It should work and works in other repos.

**Comment by robertodr** [comment]
Could it be that the master test action was not successful? The trigger for
packaging remained the same with the earliest iteration of the workflow and
the current...

**Comment by bast** [comment]
I don't understand it :man_shrugging:

**Comment by robertodr** [comment]
I don't know what I did wrong yesterday. I have just now removed the v0.5.0 tag and tagged a v0.5.0-rc1. Both the testing and packaging actions have been triggered.

Packaging fails because I forgot to update the version in `__init__.py` :facepalm:

**Comment by robertodr** [comment]
Everything works as it should now. Yay! :confetti_ball:

**Comment by bast** [comment]
Cool!
