### ISSUE TITLE
Tox and flake8

### ISSUE THREAD

**Issue by bast** [dev-cafe/parselglossy#19]
So first of all I am not sure why we use tox. For me this is just one more layer. I would use pytest directly. One motivation may be that it runs pytest and flake8 in one step.

Speaking of which I get many flake8 warnings when running locally and a non-zero exit but I don't see these on Travis which confuses me.

**Comment by bast** [comment]
OK another motivation for tox may be that we abstract the testing with respect to platform and do not have to repeat the two commands for each CI config file?

This is what I see locally but not on Travis:
```
parselglossy/cli.py:20:80: E501 line too long (102 > 79 characters)
parselglossy/token_actions.py:20:80: E501 line too long (102 > 79 characters)
parselglossy/token_actions.py:86:5: E265 block comment should start with '# '
parselglossy/__init__.py:20:80: E501 line too long (102 > 79 characters)
parselglossy/parselglossy.py:20:80: E501 line too long (102 > 79 characters)
parselglossy/atoms.py:20:80: E501 line too long (102 > 79 characters)
parselglossy/standard_grammar.py:20:80: E501 line too long (102 > 79 characters)
parselglossy/standard_grammar.py:29:1: F401 'pyparsing.Forward' imported but unused
parselglossy/standard_grammar.py:29:1: F401 'pyparsing.Optional' imported but unused
parselglossy/standard_grammar.py:29:1: F401 'pyparsing.ParseException' imported but unused
parselglossy/standard_grammar.py:29:1: F401 'pyparsing.line' imported but unused
parselglossy/standard_grammar.py:29:1: F401 'pyparsing.lineno' imported but unused
parselglossy/standard_grammar.py:30:80: E501 line too long (80 > 79 characters)
parselglossy/standard_grammar.py:62:80: E501 line too long (84 > 79 characters)
parselglossy/standard_grammar.py:69:5: E265 block comment should start with '# '
parselglossy/standard_grammar.py:118:5: E265 block comment should start with '# '
parselglossy/standard_grammar.py:120:5: E265 block comment should start with '# '
parselglossy/standard_grammar.py:122:5: E265 block comment should start with '# '
parselglossy/getkw_grammar.py:20:80: E501 line too long (102 > 79 characters)
```

**Comment by robertodr** [comment]
This is stuff that came in with the cookie cutter and I was not sure at the time whether needed or not for testing on multiple versions of Python. I do not use tox locally, as it is - ahem - hard to have multiple Python versions on NixOS... Since I am not dogfooding, I would advise for slash-and-burn, the bar being all tests on all platforms should pass.

**Comment by bast** [comment]
OK - I will remove it after I prototype the validation (to not delay things).

**Comment by robertodr** [comment]
:+1: thanks!

**Comment by robertodr** [comment]
The "line too long" checker should either be disabled or configured to make sense with the YAPF setting.

**Comment by robertodr** [comment]
After scratching my head for a bit on why Hypothesis was not being installed on the other PR, I went in and de-tox-ified in #21.
