### ISSUE TITLE
Consolidate specification of dependencies

### ISSUE THREAD

**Issue by robertodr** [dev-cafe/parselglossy#22]
We have dependencies for development (specified in `Pipfile`), testing (installed with `pip` on CI services, see the YAML files), and deployment (installed with `pip install parselglossy`).
This is problematic as we can easily lose track of dependencies in this way.

**Comment by bast** [comment]
One way would be to put everything into `setup.py` but then the user will pull in dependencies they don't need.

Probably we will need two places. But we should try to remove explicit dependencies from the CI recipe files.

**Comment by robertodr** [comment]
Possible solutions:
- List everything in `setup.py` and do `pip install  -e .` on CI. Drawback: 
  1. installing the published package would pull in `pytest` and company.
  2. We still need the `Pipfile` to install development tools like the language server and mypy.
- On CI do `pipenv install --dev -e .`. Drawback: CI runs in virtual environment already.

**Comment by bast** [comment]
> * On CI do `pipenv install --dev -e .`. Drawback: CI runs in virtual environment already.

I am not sure I see the problem with this approach.

**Comment by robertodr** [comment]
Actually, no drawbacks, just a warning from Pipenv that it will not create a new virtual environment.
