### ISSUE TITLE
Validation failures

### ISSUE THREAD

**Issue by robertodr** [dev-cafe/parselglossy#24]
Follow-up from #20 
It would be nice to have the validator not fail immediately, but rather keep going and prepare a report of all failures. The user might then get a chance to fix all failures at once, rather than going back and forth (fix one, rerun, fix next, rerun, etc)

**Comment by bast** [comment]
Fully agree. The early stop was convenient for me now to get the plane up from the runway but is not convenient for the users.

**Comment by bast** [comment]
So we agree that we want to report all errors instead of just the first error.

But how should the functions report/return the errors? As list of strings? Should they raise an exception or let the caller do it?

**Comment by robertodr** [comment]
Do we have monads? :smiley_cat: 
`TemplateError` raises when a predicate is invalid Python, whereas `InputError` is a predicate failing on a input, _i.e._ a genuine input error. Can we separate checking on the former, like we do for docstrings? That is a programmer's concern, I doubt the end user would want to meddle with fixing such errors. If `check_predicates_node` only can raise one type of error, then I would check and keep a list of failing nodes and return that to the caller for collation and raising:
```
if failures:
   raise InputError('\n'.join(failures))
```

**Comment by robertodr** [comment]
Collation and raising can actually be done at the end of the validation pass. I'd probably prefer this to giving library users the choice (I'd certainly forget to do it...)

**Comment by bast** [comment]
`TemplateError` is not only for invalid Python but something wrong with the input template - in other words an error done by the user of this library. In contrast, `InputErrors` are errors on the user-user side (if that makes sense).
I agree about separating the two error sources and raising at the end of validation.

**Comment by robertodr** [comment]
I see, indeed it's the one raised when docs are missing. We'll possibly need a more descriptive error. I was initially under the impression this was some base class for our own errors.

**Comment by robertodr** [comment]
`pyflakes` can be used for this validation!
```
import pyflakes.api

code = 'a => b'
pyflakes.api.check(code, 'foo')
```
which returns the number of warnings and reports:
```
foo:1:4: invalid syntax
a => b
```
the second argument is sadly needed.

**Comment by robertodr** [comment]
We'd need to set it up as to only report syntax errors though.

**Comment by bast** [comment]
My suggestion is to make the function(s) return two lists of errors: one for template- one for input-side. Feel totally free to change the exceptions. Then outside of the validation functions we should throw an error and list all errors in one go.

The errors could even form a tree which matches the input tree or the template tree - we could then print this error tree.

**Comment by robertodr** [comment]
Done in #42
