### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by robertodr** [dev-cafe/parselglossy#25]
Generation of test cases can get a bit unwieldy, given how many different "axis" there are. Hypothesis can help quite a bit and we should refactor other tests to use it.

**Comment by bast** [comment]
Also consider using `parametrize` instead of a for loop for checking of type errors.

**Comment by robertodr** [comment]
I have done some of this in #42, but there's still ample room for improvement, I think. For example, we could have a set of fixture components and then generate test inputs and references using Hypothesis to randomize the test cases.

**Comment by robertodr** [comment]
Some data regarding lines of code (obtained with cloc) in folders `parselglossy` and `tests`.
![Screenshot from 2019-03-26 13-46-58](https://user-images.githubusercontent.com/3708689/55027736-593bc700-4fdc-11e9-9c50-a97d4af75a99.png)

**Comment by bast** [comment]
Roberto did already a lot. Closing this issue since we will improve this continuously.
