### ISSUE TITLE
Strings in getkw grammar

### ISSUE THREAD

**Issue by stigrj** [dev-cafe/parselglossy#35]
* parselglossy version:  25e4337
* Python version: 3.7.0
* Operating System: Ubuntu-18.10

### Description

In good old getkw strings are accepted both with and without quotes
```
  some_string = foo
  another_string = 'bar'
  yet_another_string = "baz"
```
but the getkw grammar in parselglossy fails to accept quoteless strings if they are *part of a section*:
```
some_string = foo          # works
another_string = 'bar'     # works
yet_another_string = "baz" # works

some_section {
  some_string = foo        # fails
  another_string = 'bar'   # works
  yet_another_string "baz" # works
}
```

**Comment by stigrj** [comment]
Wait! I spoke to soon :slightly_smiling_face:  Turns out I had an underscore in the particular string that failed, so the error is **unrelated to section keywords vs standalone keywords**. The real problem is the following:
```
some_string = foo              # works
another_string = foo_bar       # fails
yet_another_string = 'foo_bar' # works
```
I still think the second option should be valid input, so I'll leave the issue open.

**Comment by robertodr** [comment]
The problem is here: https://github.com/dev-cafe/parselglossy/blob/master/parselglossy/grammars/atoms.py#L61 String are only made of alphanumeric characters, quoted (single or double quotes) or unquoted. I'll fix and add more tests.
