### ISSUE TITLE
Separate development requirements

### ISSUE THREAD

**Issue by robertodr** [dev-cafe/parselglossy#38]
The development packages in `Pipfile` are in two classes: 
1. the stuff that everyone should use to develop parselglossy, and 
2. the stuff that only I use to develop parselglossy (like the language server). 

Since it's unfair to inflict upon the world the latter, I need to figure out a way to keep the two things separate.

**Comment by bast** [comment]
(genuine curiosity questions:)
- why do others not need this/these package(s)?
- why would it be a burden for others to install it/them anyway?

**Comment by robertodr** [comment]
I think it would be very good if everybody used my same exact development workflow :smiling_imp: 

The packages under scrutiny are:
- black (code formatting)
- epc (needed to make importmagic work in Emacs)
- importmagic (checks imports)
- isort and pyls-isort (sorts imports)
- mypy and pyls-mypy (type checking within the editor)
- python-language-server with various extensions (language server)

I already have a working solution where I install the "extras" with Nix and the Pipfile is at its bare minimum. I can add documentation on how to get these extras.

The language server is a relatively new thing to turn almost every editor into an IDE with minimal configuration. It is working really well for me, but you need to install the package and do a little bit of configuration on your editor if you want to use it.

Black requires Python 3.6 and it's beta software. We would need to allow prereleases in the Pipfile, which can't be delimited to just one package and I am not super comfortable with allowing betas and alphas for all packages. Also, I cannot see how to make Pipenv fail gracefully if a package is not installable for a given version of Python. This makes CI choke for the 3.5 and 3.4 lanes. Why do I want to use Black? Because does more consistent formatting than YAPF. With the latter I've seen cases where two different versions give different formattings.

**Comment by bast** [comment]
Personally I don't see myself using the Emacs stuff very soon but I don't mind them if their installation does not fail on me.

Speaking of which personally I don't mind bumping minimum Python version to 3.6 but we should check which version a standard Ubuntu provides.

**Comment by robertodr** [comment]
:+1: on Py3.6+ only. There's two questions: a) what ships in normal distros b) what ships on clusters. How are fram and stallo doing on that front?

**Comment by robertodr** [comment]
To be clear: I want to avoid the situation where we put a lot of effort into this project and then no one adopts because of its dependencies.

**Comment by bast** [comment]
On clusters it is typically not a problem. These versions are available. I am more worried that library clients would not be up to 3.6+ or some of their other dependencies. So this is a good point to consider.
