### ISSUE TITLE
Prepare tutorials

### ISSUE THREAD

**Issue by robertodr** [dev-cafe/parselglossy#41]
We need to prepare tutorials on how to use the library. We will need different tutorials ranging from basic to advanced uses:
Basic/getting started:
- Using the library in a Python code. This will show how to use actual input files and plain `dict`-s.
- How to go from installing the library, adopting one of the available grammars, and hook it up to a program in a compiled language. The ancillary repository for C++, C, and Fortran should be ready for this purpose.

Intermediate:
- Composing inputs with different grammars.

Advanced:
- Defining new grammars. This is needed, but I don't want to write a pyparsing tutorial.

**Comment by stigrj** [comment]
I can have a go on some of the basic parts, but not until next week.

**Comment by robertodr** [comment]
Thanks!

**Comment by stigrj** [comment]
Do you have some standard input example you want to use in `cpp-parselglossy` etc.?

**Comment by robertodr** [comment]
No :sweat_smile:

**Comment by bast** [comment]
Fortran and C tutorials are missing. We will add a Fortran example as soon as we get (LS)Dalton parsing example to work.

**Comment by robertodr** [comment]
The repositories for C++, C, and Fortran exist. They probably need to be updated, but this issue has been dealt with.
