### ISSUE TITLE
Drop support for Python 3.4?

### ISSUE THREAD

**Issue by bast** [dev-cafe/parselglossy#43]
I would :-)

Python 3.4 reached end of life yesterday:
https://devguide.python.org/#status-of-python-branches

**Comment by robertodr** [comment]
I'd drop even 3.5 and test on 3.6, 3.7, and development version only. I've had enought of the contortions that I have had to play to test error messages (since `dict` items come in arbitrary order, also multiple error messages appear in arbitrary order...)

**Comment by robertodr** [comment]
@stigrj how does this proposal look on your side? How hard it is to use pyenv or conda to get updated Python versions on the cluster? If we have good enough docs on how to get the minimal supported Python it should be fine.

**Comment by bast** [comment]
I recommend that we go step by step - I think it is fairly safe to drop 3.4. And we can re-evaluate later versions once they become too painful to carry.

**Comment by robertodr** [comment]
Python 3.4 support dropped in #42
