### ISSUE TITLE
Documentation field name: "docstring" vs "documentation" vs something else

### ISSUE THREAD

**Issue by robertodr** [dev-cafe/parselglossy#44]
With #42 I renamed `documentation` to `docstring`. @bast commented: "would someone who has never heard of `docstrings` know what this is? Is `documentation` more intuitive? Also `docstrings` are really for documentation extracted out of source code and I am not sure whether the input blueprint counts as source code."
The only reason why I did the rename is that I consistently misspell "documentation" when coding and I think it's a bit too long of a name for a field.
Let us discuss and agree on something.

**Comment by bast** [comment]
We discussed and decided to keep `docstring`.
