### ISSUE TITLE
Add a Path type

### ISSUE THREAD

**Issue by robertodr** [dev-cafe/parselglossy#55]
In the discussion over #51 it emerged that filesystem paths should be allowed to have richer semantics than that allowed by simple strings.

**Comment by robertodr** [comment]
I don't think a specific `path` type is needed. Casting to a Python `Path` is actually counterproductive, as it can be natively serialized to JSON. Even that were possible, deserialization in any other language would surely lead to surprises. A case-sensitive string type would capture the need to skip case normalization and checks on paths could still be performed easily.

**Comment by bast** [comment]
We concluded that we will not do this. We stick with `str` type for paths and since we do not automatically normalize values, not a problem.
