### ISSUE TITLE
Circular dependencies in default and predicate callables?

### ISSUE THREAD

**Issue by robertodr** [dev-cafe/parselglossy#73]
Can we have circular dependencies in default and predicate callables? If not, we need to document why. If yes, we need a way to stop parsing with a meaningful error message.

**Comment by bast** [comment]
I see two options:
- we detect circular dependencies and stop with a nice error
- we allow them but ignore them but we only apply "from top to bottom", single-pass

My preference goes to detecting and stopping to avoid surprises.

**Comment by robertodr** [comment]
Agreed on detect-and-stop. Not so clear how you'd detect though.

**Comment by bast** [comment]
We can build a graph of dependencies as we go through the tokens and then we check whether the graph is circular.

**Comment by robertodr** [comment]
Sounds good, hopefully there's a library for that :smile:

**Comment by bast** [comment]
I am tempted to program this myself as a little challenge. There are codes and libraries but they seem to be  not lightweight for this relatively simple task.

**Comment by bast** [comment]
I see a graph as a dictionary mapping `a` to `List[a]`.

I thought about it some more and I see no difficulties detecting cycles in a graph - the difficulty that I see is to translate defaults (and predicates?) into a graph since we use eval there and don't directly have access to the nodes of the graph.

**Comment by robertodr** [comment]
Closed in favor of #76 which has an actual example of chained dependencies which might degenerate into being circular.
