### ISSUE TITLE
Add page linking to codes using parselglossy

### ISSUE THREAD

**Issue by robertodr** [dev-cafe/parselglossy#75]
Should it be a section in the README or in the documentation proper or both?

**Comment by bast** [comment]
I think README - since README is often the first entry point and it's nice to show that the lib is used. Then if we want to we can also list on the doc pages.

**Comment by robertodr** [comment]
@stigrj can you update the README with a link to MRChem? It would be nice to also have a sentence that invites users to send PRs to include their codes in the list.

**Comment by robertodr** [comment]
This was solved in #105 Thanks @stigrj!
