### ISSUE TITLE
--doctest-module flag is not recognized

### ISSUE THREAD

**Issue by bast** [dev-cafe/parselglossy#80]
Fails PRs on Travis and my laptop:
https://github.com/dev-cafe/parselglossy/blob/master/.travis.yml#L19

I think it's supposed to be `--doctest-modules`.

**Comment by robertodr** [comment]
Surprised that it's only now popping up. As I commented in #81, that flag can be completely removed as doctest-style testing is not used in the project.

**Comment by robertodr** [comment]
Fixed in #82
