### ISSUE TITLE
Autogenerate list of authors in docs from AUTHORS.rst

### ISSUE THREAD

**Issue by robertodr** [dev-cafe/parselglossy#9]
We have:
- `__init__.py` defines various fields like `__author__` and `__maintainers__` and `__credits__` which are not widely used, I think. 
- `AUTHORS.rst`, which is more widely recognized and could be used more formally for authorship recognition.
- the `author` variable in `docs/conf.py` which Sphinx uses.

It would be good to consolidate these, so we only need to update in one place. I personally favor using `AUTHORS.rst` exclusively, only put `__version__` and `__all__` in `__init__.py`, and do some regex magic in `conf.py` to update the `author` variable.

**Comment by bast** [comment]
I agree 100%

**Comment by robertodr** [comment]
@bast could you manage to have a look at this one together with #54 when minting 0.3.0?

**Comment by bast** [comment]
Importing the names to `conf.py` is no problem.

Extracting names from `AUTHORS.rst` is not difficult but could be brittle. How about we keep `AUTHORS.rst` and `__init__.py`? The latter is the one which is used to extract data to `setup.py` and `conf.py`. The former is "freestyle" and for humans.

**Comment by robertodr** [comment]
Works for me!

**Comment by bast** [comment]
OK - I will fix that tomorrow.
