### ISSUE TITLE
Consider adding Union type

### ISSUE THREAD

**Issue by robertodr** [dev-cafe/parselglossy#98]
I was thinking about cases where a given keyword might be either a list or just a scalar, that is `Union[int, List[int]]` (or similar) Do you think this is a good idea? I don't know exactly how it would look in the implementation.

**Comment by bast** [comment]
What would be an example for such a keyword?

**Comment by robertodr** [comment]
For example, when specifying states per irrep in a response calculation. I might either want to say explicitly 3 per irrep: `[3, 3, 3, 3]` or a total number. I admit it's a very narrow use case.

**Comment by bast** [comment]
We can add it but if this was my code, I would prefer:
```
num_states_per_irrep: [1, 2, 3, 4]
num_states_total: 10
```
or:
```
num_states_irrep:
    0: 1
    all: 10
```

I would not like to check inside whether something is a list type or not.
I am not sure what would be better (less surprising, less error prone, explicit is better than implicit) from the user perspective.

**Comment by robertodr** [comment]
Shelving as:
- The design is tricky.
- It can be achieved in an "explicit is better than implicit" fashion.
- I don't have time to prototype it anyway.
